//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_agile_kelas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHeader
    {
        public int transactionId { get; set; }
        public long userId { get; set; }
        public int transactionTypeId { get; set; }
        public string itemDescription { get; set; }
        public int price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
        public virtual User User { get; set; }
    }
}
